version: '3.8'
services:
  db:
    image: postgres:15
    container_name: assetserve_db
    restart: always
    environment:
      POSTGRES_USER: malhar
      POSTGRES_PASSWORD: malhar@passionfruit@123f
      POSTGRES_DB: assetserve_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: